### eliminar una pelicula por id
DELETE http://localhost:3000/peliculas/BB3CD5E6420D11F1BE635CBAEF497F34

### actualizar pelicula con metodo patch
PATCH http://localhost:3000/peliculas/457CE8AD437411F195EA5CBAEF497F3
Content-Type: application/json

{
    "SQL": "DELETE * from peliculas",
    "title": "Ultima prueba de hoy erronea",
    "year": 1995,
    "director": "hola",
    "duration": 100,
    "poster": "http://www.google.com"
}

### agregar pelicula con post
POST http://localhost:3000/peliculas/
Content-Type: application/json

{
    "title": "Sin embargo",
    "year": 2004,
    "director": "Alvaro delgado",
    "duration": 400,
    "poster": "https://www.google.com/imgres?q=Spider-Man%3A%20Across%20the%20Spider-Verse&imgurl=https%3A%2F%2Fmedia.es.wired.com%2Fphotos%2F647a13d588218b01bf4a1c5f%2F4%3A3%2Fw_1800%2Ch_1350%2Cc_limit%2FSpider-Man-Across-The-Spider-Verse-Monitor-Culture.jpg&imgrefurl=https%3A%2F%2Fes.wired.com%2Farticulos%2Fspider-man-across-the-spider-verse-tiene-todo-lo-que-le-falta-al-mcu&docid=XXycGNM1GCULdM&tbnid=nclHVafHEARsXM&vet=12ahUKEwi-xqmHu56TAxW6le4BHTcIGcQQnPAOegQIJxAB..i&w=1800&h=1350&hcb=2&ved=2ahUKEwi-xqmHu56TAxW6le4BHTcIGcQQnPAOegQIJxABCCC",
    "rate": 9.9,
    "genre": [
        "Crime"
    ]
}

### cargar un genero de peliculas
GET http://localhost:3000/peliculas?genero=sci-fi

### cargar pelicula por id
GET http://localhost:3000/peliculas/457CE8AD437411F195EA5CBAEF497F34

### cargar todas las peliculas
GET http://localhost:3000/peliculas

### cargar pokemon por nombre
GET http://localhost:1234/pokemon/ditto

### esto sera la separacion de request
POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "dit",
    "type": "norm",
    "moves": [
        "transformarse"
    ]
}