GET http://localhost:1234/pokemon/ditto

### esto sera la separacion de request

POST http://localhost:1234/pokemon
Content-Type: application/json

{
    "name": "dit",
    "type": "norm",
    "moves": [
        "transformarse"
    ]
}